// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiWA8BdCahuxOOlRIc3gKFFASwgPHbqfY',
    appId: '1:160238399820:web:18a6a8d74b241a05965fe9',
    messagingSenderId: '160238399820',
    projectId: 'mappa-6aa71',
    authDomain: 'mappa-6aa71.firebaseapp.com',
    storageBucket: 'mappa-6aa71.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSAr0cI7jSJrS6snzLOInmPtUPOOm8fxM',
    appId: '1:160238399820:android:5e72df62f075c42c965fe9',
    messagingSenderId: '160238399820',
    projectId: 'mappa-6aa71',
    storageBucket: 'mappa-6aa71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1ZalIEWHCGfLvJXz0QsULVWOe8ab_bGM',
    appId: '1:160238399820:ios:5697fda454f34cf8965fe9',
    messagingSenderId: '160238399820',
    projectId: 'mappa-6aa71',
    storageBucket: 'mappa-6aa71.appspot.com',
    iosBundleId: 'com.example.mappaIndicatore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1ZalIEWHCGfLvJXz0QsULVWOe8ab_bGM',
    appId: '1:160238399820:ios:5697fda454f34cf8965fe9',
    messagingSenderId: '160238399820',
    projectId: 'mappa-6aa71',
    storageBucket: 'mappa-6aa71.appspot.com',
    iosBundleId: 'com.example.mappaIndicatore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiWA8BdCahuxOOlRIc3gKFFASwgPHbqfY',
    appId: '1:160238399820:web:c97f84771d62da28965fe9',
    messagingSenderId: '160238399820',
    projectId: 'mappa-6aa71',
    authDomain: 'mappa-6aa71.firebaseapp.com',
    storageBucket: 'mappa-6aa71.appspot.com',
  );
}
